name: JustForceSpawn
version: '${project.version}'
main: com.krizind.justforcespawn
api-version: 1.17
authors: [ Kriiiiiiiz ]
description: A simple and lightweight plugin that automatically teleports players to spawn when they join the server.
website: www.krizind.com
commands:
  setspawn:
    description: Sets spawn point.
  spawn:
    description: Teleports to spawn.
